##### Beyond VaR: 02 — EVT / POT
##### Requires var_results_part2.csv generated by 01_stressed_var.py
##### Download data files from the beyond-var/ folder in this repository,
##### then update DATA_PATH below to match your local directory.

import pandas as pd
import numpy as np
from scipy import stats
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

DATA_PATH = r"C:/Users/your_username/Downloads/"  # update this to your local path

returns = pd.read_csv(DATA_PATH + "returns.csv", index_col=0, parse_dates=True)
results = pd.read_csv(DATA_PATH + "var_results_part2.csv", index_col=0, parse_dates=True)
spy_ret = returns["SPY"].reindex(results.index)
losses_series = -spy_ret

REGIME_COLORS = {
    "Pre-GFC":       "#4878CF",
    "GFC":           "#D65F5F",
    "Recovery":      "#6ACC65",
    "Low-Vol Bull":  "#B47CC7",
    "COVID":         "#C4AD66",
    "Post-COVID":    "#77BEDB",
    "2022 Bear":     "#D65F5F",
    "2023 Recovery": "#6ACC65",
    "2024 AI Rally": "#4878CF",
    "2025-2026":     "#B47CC7",
}

def add_regime_bands(ax):
    for regime, color in REGIME_COLORS.items():
        sub = results[results["Regime"] == regime]
        if len(sub) == 0:
            continue
        ax.axvspan(sub.index[0], sub.index[-1], alpha=0.08, color=color)

def kupiec_test(exceptions, n, p=0.01):
    x = exceptions.sum()
    if x == 0 or x == n:
        return np.nan, np.nan
    p_hat = x / n
    lr    = -2 * (x * np.log(p / p_hat) + (n - x) * np.log((1 - p) / (1 - p_hat)))
    return round(lr, 4), round(1 - stats.chi2.cdf(lr, df=1), 4)

def christoffersen_test(exceptions):
    ex = exceptions.values
    n00 = n01 = n10 = n11 = 0
    for t in range(1, len(ex)):
        if   ex[t-1]==0 and ex[t]==0: n00+=1
        elif ex[t-1]==0 and ex[t]==1: n01+=1
        elif ex[t-1]==1 and ex[t]==0: n10+=1
        elif ex[t-1]==1 and ex[t]==1: n11+=1
    p01 = n01/(n00+n01) if (n00+n01)>0 else 0
    p11 = n11/(n10+n11) if (n10+n11)>0 else 0
    p   = (n01+n11)/(n00+n01+n10+n11)
    if p==0 or p==1 or p01==0 or p01==1 or p11==0 or p11==1:
        return np.nan, np.nan
    lr = -2*(
        (n00+n10)*np.log(1-p) + (n01+n11)*np.log(p) -
        n00*np.log(1-p01) - n01*np.log(p01) -
        n10*np.log(1-p11) - n11*np.log(p11)
    )
    return round(lr, 4), round(1 - stats.chi2.cdf(lr, df=1), 4)

def traffic_light(n):
    if n <= 4:   return "Green"
    elif n <= 9: return "Yellow"
    else:        return "Red"

def fit_gpd(exceedances):
    def neg_ll(params):
        xi, beta = params
        if beta <= 0:
            return np.inf
        if xi != 0:
            if np.any(1 + xi * exceedances / beta <= 0):
                return np.inf
            return np.sum(np.log(beta) + (1 + 1/xi) * np.log(1 + xi * exceedances / beta))
        else:
            return np.sum(np.log(beta) + exceedances / beta)
    result = minimize(neg_ll, x0=[0.1, np.std(exceedances)], method="Nelder-Mead")
    return result.x

def evt_var_es(losses, threshold_quantile=0.95, conf=0.99):
    u      = np.quantile(losses, threshold_quantile)
    excess = losses[losses > u] - u
    n      = len(losses)
    n_u    = len(excess)
    if n_u < 10:
        return np.nan, np.nan, np.nan, np.nan
    xi, beta = fit_gpd(excess)
    p = 1 - conf
    if xi != 0:
        var = u + (beta/xi) * (((p * n / n_u) ** (-xi)) - 1)
        es  = (var + beta - xi * u) / (1 - xi)
    else:
        var = u + beta * np.log(p * n / n_u)
        es  = var + beta
    if var <= 0 or es <= 0 or es < var:
        return np.nan, np.nan, xi, beta
    return var, es, xi, beta

WINDOW = 250

evt_var_out = np.full(len(results), np.nan)
evt_es_out  = np.full(len(results), np.nan)
xi_out      = np.full(len(results), np.nan)
beta_out    = np.full(len(results), np.nan)

print("Rolling EVT...")
for t in range(WINDOW, len(losses_series)):
    window_losses = losses_series.iloc[t - WINDOW:t].values
    window_losses = window_losses[~np.isnan(window_losses)]
    if len(window_losses) < WINDOW:
        continue
    var, es, xi, beta = evt_var_es(window_losses)
    evt_var_out[t] = var
    evt_es_out[t]  = es
    xi_out[t]      = xi
    beta_out[t]    = beta
    if t % 500 == 0:
        print(f"  progress: {t}/{len(losses_series)} ({t/len(losses_series)*100:.1f}%)")
print("Done.")

results["EVT_VaR"]  = evt_var_out
results["EVT_ES"]   = evt_es_out
results["EVT_xi"]   = xi_out
results["EVT_beta"] = beta_out

results["Ex_EVT_VaR"] = (results["Return"] < -results["EVT_VaR"]).astype(int)
results["Ex_EVT_ES"]  = (results["Return"] < -results["EVT_ES"]).astype(int)

all_models = [
    ("Parametric",      "Ex_Param"),
    ("HS",              "Ex_HS"),
    ("FHS",             "Ex_FHS"),
    ("sVaR (Combined)", "Ex_sVaR_Combined"),
    ("EVT VaR",         "Ex_EVT_VaR"),
    ("EVT ES",          "Ex_EVT_ES"),
]

print(f"\n{'Model':<20} {'Exceptions':>10} {'Rate':>8} {'Kupiec_p':>10} {'CC_p':>10} {'Zone':>8}")
print("-" * 70)

for name, col in all_models:
    ex       = results[col].dropna()
    x        = int(ex.sum())
    n        = len(ex)
    _, kup_p = kupiec_test(ex, n)
    _, cc_p  = christoffersen_test(ex)
    zone     = traffic_light(x)
    print(f"{name:<20} {x:>10} {x/n:>8.4f} {str(kup_p):>10} {str(cc_p):>10} {zone:>8}")

xi_series   = pd.Series(xi_out,   index=results.index).dropna()
beta_series = pd.Series(beta_out, index=results.index).dropna()
print(f"\nGPD Parameters (full-period average):")
print(f"  xi  (shape): {xi_series.mean():.4f}")
print(f"  beta (scale): {beta_series.mean():.4f}")

full_losses = losses_series.dropna().values
thresholds  = np.percentile(full_losses, np.arange(80, 99))
mean_excess = [full_losses[full_losses > u].mean() - u for u in thresholds]

fig1, ax = plt.subplots(figsize=(12, 5))
ax.plot(thresholds * 100, [m * 100 for m in mean_excess],
        color="#2166AC", linewidth=2, marker="o", markersize=5)
ax.axvline(np.percentile(full_losses, 95) * 100,
           color="#D6604D", linewidth=1.5, linestyle="--", label="95th percentile threshold")
ax.set_xlabel("Threshold (%)", fontsize=13)
ax.set_ylabel("Mean Excess Loss (%)", fontsize=13)
ax.set_title("Mean Excess Plot — SPY Daily Losses", fontsize=14, fontweight="bold")
ax.legend(fontsize=12)
ax.grid(alpha=0.3)
ax.tick_params(axis="both", labelsize=12)
plt.tight_layout()
plt.savefig(DATA_PATH + "fig_evt1_mean_excess.png", dpi=150, bbox_inches="tight")
plt.show()

u            = np.percentile(full_losses, 95)
excess       = full_losses[full_losses > u] - u
xi_fit, beta_fit = fit_gpd(excess)
x_range  = np.linspace(0, excess.max(), 200)
gpd_cdf  = 1 - (1 + xi_fit * x_range / beta_fit) ** (-1/xi_fit)
emp_x    = np.sort(excess)
emp_cdf  = np.arange(1, len(emp_x)+1) / len(emp_x)

fig2, ax = plt.subplots(figsize=(12, 5))
ax.plot(emp_x * 100, emp_cdf, color="gray", linewidth=1.5, label="Empirical CDF")
ax.plot(x_range * 100, gpd_cdf, color="#D6604D", linewidth=2,
        label=f"GPD Fit (xi={xi_fit:.3f}, beta={beta_fit*100:.3f}%)")
ax.set_xlabel("Excess Loss above Threshold (%)", fontsize=13)
ax.set_ylabel("CDF", fontsize=13)
ax.set_title("GPD Tail Fit — SPY Excess Losses above 95th Percentile", fontsize=14, fontweight="bold")
ax.legend(fontsize=12)
ax.grid(alpha=0.3)
ax.tick_params(axis="both", labelsize=12)
plt.tight_layout()
plt.savefig(DATA_PATH + "fig_evt2_gpd_fit.png", dpi=150, bbox_inches="tight")
plt.show()

fig3, axes = plt.subplots(2, 1, figsize=(18, 12), sharex=True)
fig3.suptitle("EVT VaR and ES vs Actual Returns (2005-2026)\n99% VaR / 97.5% ES",
              fontsize=16, fontweight="bold")

for ax, (col, ex_col, title, color) in zip(axes, [
    ("EVT_VaR", "Ex_EVT_VaR", "EVT VaR (99%)",  "#7B2D8B"),
    ("EVT_ES",  "Ex_EVT_ES",  "EVT ES (97.5%)", "#1A9850"),
]):
    add_regime_bands(ax)
    losses = results["Return"].clip(upper=0)
    ax.fill_between(results.index, losses, 0, color="gray", alpha=0.4, label="Actual Loss")
    ax.plot(results.index, -results[col], color=color, linewidth=1.0, label=title)
    ex_dates = results[results[ex_col] == 1]
    ax.scatter(ex_dates.index, ex_dates["Return"],
               color="black", s=12, zorder=5, label=f"Exception (n={len(ex_dates)})")
    ax.set_ylabel("Daily Return", fontsize=13)
    ax.set_title(title, fontsize=13, fontweight="bold")
    ax.legend(loc="lower left", fontsize=11)
    ax.set_ylim(-0.15, 0.05)
    ax.axhline(0, color="black", linewidth=0.5)
    ax.grid(axis="y", alpha=0.3)
    ax.tick_params(axis="both", labelsize=12)

plt.tight_layout()
plt.savefig(DATA_PATH + "fig_evt3_var_es.png", dpi=150, bbox_inches="tight")
plt.show()

regime_order = [
    "Pre-GFC","GFC","Recovery","Low-Vol Bull",
    "COVID","Post-COVID","2022 Bear",
    "2023 Recovery","2024 AI Rally","2025-2026"
]

summary = []
for regime in regime_order:
    sub = results[results["Regime"] == regime]
    if len(sub) == 0:
        continue
    summary.append({
        "Regime":          regime,
        "FHS":             sub["Ex_FHS"].sum(),
        "sVaR (Combined)": sub["Ex_sVaR_Combined"].sum(),
        "EVT VaR":         sub["Ex_EVT_VaR"].sum(),
        "EVT ES":          sub["Ex_EVT_ES"].sum(),
        "Theory":          round(len(sub) * 0.01, 1),
    })
sumdf = pd.DataFrame(summary)

fig4, ax = plt.subplots(figsize=(18, 7))
x     = np.arange(len(sumdf))
width = 0.18
ax.bar(x - 1.5*width, sumdf["FHS"],             width, label="FHS (baseline)", color="#D6604D", alpha=0.85)
ax.bar(x - 0.5*width, sumdf["sVaR (Combined)"], width, label="sVaR (Combined)",color="#7B2D8B", alpha=0.85)
ax.bar(x + 0.5*width, sumdf["EVT VaR"],         width, label="EVT VaR",        color="#2166AC", alpha=0.85)
ax.bar(x + 1.5*width, sumdf["EVT ES"],          width, label="EVT ES",         color="#1A9850", alpha=0.85)
ax.step(x, sumdf["Theory"], where="mid", color="black", linewidth=2, linestyle="--", label="Theory (1%)")
ax.axhline(4,  color="#1A9850", linestyle=":", linewidth=1.5, alpha=0.8)
ax.axhline(9,  color="#FFA500", linestyle=":", linewidth=1.5, alpha=0.8)
ax.axhline(10, color="#D65F5F", linestyle=":", linewidth=1.5, alpha=0.8)
ax.set_xticks(x)
ax.set_xticklabels(sumdf["Regime"], rotation=25, ha="right", fontsize=12)
ax.set_ylabel("Number of Exceptions", fontsize=13)
ax.set_title("EVT Models vs FHS and Stressed — Exceptions by Regime", fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig(DATA_PATH + "fig_evt4_regime.png", dpi=150, bbox_inches="tight")
plt.show()

results.to_csv(DATA_PATH + "var_results_part2.csv")
print("Saved.")
