##### Beyond VaR: 03 — GARCH Extensions (GJR-GARCH, t-GARCH, GARCH-EVT)
##### Requires var_results_part2.csv generated by 02_evt_pot.py
##### Download data files from the beyond-var/ folder in this repository,
##### then update DATA_PATH below to match your local directory.

import pandas as pd
import numpy as np
from scipy import stats
from scipy.optimize import minimize
from arch import arch_model
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

DATA_PATH = r"C:/Users/your_username/Downloads/"  # update this to your local path

returns = pd.read_csv(DATA_PATH + "returns.csv", index_col=0, parse_dates=True)
results = pd.read_csv(DATA_PATH + "var_results_part2.csv", index_col=0, parse_dates=True)
spy_ret = returns["SPY"].reindex(results.index)

REGIME_COLORS = {
    "Pre-GFC":       "#4878CF",
    "GFC":           "#D65F5F",
    "Recovery":      "#6ACC65",
    "Low-Vol Bull":  "#B47CC7",
    "COVID":         "#C4AD66",
    "Post-COVID":    "#77BEDB",
    "2022 Bear":     "#D65F5F",
    "2023 Recovery": "#6ACC65",
    "2024 AI Rally": "#4878CF",
    "2025-2026":     "#B47CC7",
}

def add_regime_bands(ax):
    for regime, color in REGIME_COLORS.items():
        sub = results[results["Regime"] == regime]
        if len(sub) == 0:
            continue
        ax.axvspan(sub.index[0], sub.index[-1], alpha=0.08, color=color)

def kupiec_test(exceptions, n, p=0.01):
    x = exceptions.sum()
    if x == 0 or x == n:
        return np.nan, np.nan
    p_hat = x / n
    lr    = -2 * (x * np.log(p / p_hat) + (n - x) * np.log((1 - p) / (1 - p_hat)))
    return round(lr, 4), round(1 - stats.chi2.cdf(lr, df=1), 4)

def christoffersen_test(exceptions):
    ex = exceptions.values
    n00 = n01 = n10 = n11 = 0
    for t in range(1, len(ex)):
        if   ex[t-1]==0 and ex[t]==0: n00+=1
        elif ex[t-1]==0 and ex[t]==1: n01+=1
        elif ex[t-1]==1 and ex[t]==0: n10+=1
        elif ex[t-1]==1 and ex[t]==1: n11+=1
    p01 = n01/(n00+n01) if (n00+n01)>0 else 0
    p11 = n11/(n10+n11) if (n10+n11)>0 else 0
    p   = (n01+n11)/(n00+n01+n10+n11)
    if p==0 or p==1 or p01==0 or p01==1 or p11==0 or p11==1:
        return np.nan, np.nan
    lr = -2*(
        (n00+n10)*np.log(1-p) + (n01+n11)*np.log(p) -
        n00*np.log(1-p01) - n01*np.log(p01) -
        n10*np.log(1-p11) - n11*np.log(p11)
    )
    return round(lr, 4), round(1 - stats.chi2.cdf(lr, df=1), 4)

def traffic_light(n):
    if n <= 4:   return "Green"
    elif n <= 9: return "Yellow"
    else:        return "Red"

def fit_gpd(exceedances):
    def neg_ll(params):
        xi, beta = params
        if beta <= 0:
            return np.inf
        if xi != 0:
            if np.any(1 + xi * exceedances / beta <= 0):
                return np.inf
            return np.sum(np.log(beta) + (1 + 1/xi) * np.log(1 + xi * exceedances / beta))
        else:
            return np.sum(np.log(beta) + exceedances / beta)
    result = minimize(neg_ll, x0=[0.1, np.std(exceedances)], method="Nelder-Mead")
    return result.x

WINDOW = 250
CONF   = 0.99

def rolling_gjr(r, window=WINDOW):
    data = r.dropna().values * 100
    n    = len(data)
    out  = np.full(n, np.nan)
    for t in range(window, n):
        try:
            w      = data[t - window:t]
            res    = arch_model(w, vol="GARCH", p=1, o=1, q=1,
                                dist="normal", rescale=False).fit(disp="off")
            sig_t1 = np.sqrt(res.forecast(horizon=1).variance.values[-1, 0])
            q_res  = np.percentile(res.std_resid, (1 - CONF) * 100)
            out[t] = -(sig_t1 * q_res) / 100
        except Exception:
            out[t] = np.nan
        if t % 500 == 0:
            print(f"  GJR progress: {t}/{n} ({t/n*100:.1f}%)")
    return pd.Series(out, index=r.index)

def rolling_tgarch(r, window=WINDOW):
    data = r.dropna().values * 100
    n    = len(data)
    out  = np.full(n, np.nan)
    for t in range(window, n):
        try:
            w      = data[t - window:t]
            res    = arch_model(w, vol="GARCH", p=1, q=1,
                                dist="t", rescale=False).fit(disp="off")
            sig_t1 = np.sqrt(res.forecast(horizon=1).variance.values[-1, 0])
            q_res  = np.percentile(res.std_resid, (1 - CONF) * 100)
            out[t] = -(sig_t1 * q_res) / 100
        except Exception:
            out[t] = np.nan
        if t % 500 == 0:
            print(f"  t-GARCH progress: {t}/{n} ({t/n*100:.1f}%)")
    return pd.Series(out, index=r.index)

def rolling_garch_evt(r, window=WINDOW, threshold_q=0.95):
    data = r.dropna().values * 100
    n    = len(data)
    out  = np.full(n, np.nan)
    for t in range(window, n):
        try:
            w      = data[t - window:t]
            res    = arch_model(w, vol="GARCH", p=1, q=1,
                                dist="normal", rescale=False).fit(disp="off")
            sig_t1 = np.sqrt(res.forecast(horizon=1).variance.values[-1, 0])
            resid  = res.std_resid
            losses = -resid
            u      = np.quantile(losses, threshold_q)
            excess = losses[losses > u] - u
            n_w    = len(resid)
            n_u    = len(excess)
            if n_u < 5:
                out[t] = np.nan
                continue
            xi, beta = fit_gpd(excess)
            p_val    = 1 - CONF
            if xi != 0:
                q_evt = u + (beta/xi) * (((p_val * n_w / n_u) ** (-xi)) - 1)
            else:
                q_evt = u + beta * np.log(p_val * n_w / n_u)
            var = -(sig_t1 * (-q_evt)) / 100
            out[t] = var if var > 0 else np.nan
        except Exception:
            out[t] = np.nan
        if t % 500 == 0:
            print(f"  GARCH-EVT progress: {t}/{n} ({t/n*100:.1f}%)")
    return pd.Series(out, index=r.index)

print("GJR-GARCH...")
gjr_var = rolling_gjr(spy_ret)
print("Done.\n")

print("t-GARCH...")
tgarch_var = rolling_tgarch(spy_ret)
print("Done.\n")

print("GARCH-EVT...")
garch_evt_var = rolling_garch_evt(spy_ret)
print("Done.\n")

results["GJR_VaR"]       = gjr_var.reindex(results.index).values
results["tGARCH_VaR"]    = tgarch_var.reindex(results.index).values
results["GARCH_EVT_VaR"] = garch_evt_var.reindex(results.index).values

results["Ex_GJR"]       = (results["Return"] < -results["GJR_VaR"]).astype(int)
results["Ex_tGARCH"]    = (results["Return"] < -results["tGARCH_VaR"]).astype(int)
results["Ex_GARCH_EVT"] = (results["Return"] < -results["GARCH_EVT_VaR"]).astype(int)

all_models = [
    ("Parametric",  "Ex_Param"),
    ("HS",          "Ex_HS"),
    ("FHS",         "Ex_FHS"),
    ("GJR-GARCH",   "Ex_GJR"),
    ("t-GARCH",     "Ex_tGARCH"),
    ("GARCH-EVT",   "Ex_GARCH_EVT"),
]

print(f"\n{'Model':<20} {'Exceptions':>10} {'Rate':>8} {'Kupiec_p':>10} {'CC_p':>10} {'Zone':>8}")
print("-" * 70)

for name, col in all_models:
    ex       = results[col].dropna()
    x        = int(ex.sum())
    n        = len(ex)
    _, kup_p = kupiec_test(ex, n)
    _, cc_p  = christoffersen_test(ex)
    zone     = traffic_light(x)
    print(f"{name:<20} {x:>10} {x/n:>8.4f} {str(kup_p):>10} {str(cc_p):>10} {zone:>8}")

plot_models = [
    ("GJR_VaR",       "Ex_GJR",       "GJR-GARCH (Leverage Effect)",      "#E07B39"),
    ("tGARCH_VaR",    "Ex_tGARCH",    "t-GARCH (Fat-Tailed Innovations)", "#1A9850"),
    ("GARCH_EVT_VaR", "Ex_GARCH_EVT", "GARCH-EVT",                        "#7B2D8B"),
]

fig1, axes = plt.subplots(3, 1, figsize=(18, 16), sharex=True)
fig1.suptitle("GARCH Extensions vs FHS (2005-2026)\n99% Confidence, 1-Day Holding Period",
              fontsize=16, fontweight="bold")

for ax, (var_col, ex_col, title, color) in zip(axes, plot_models):
    add_regime_bands(ax)
    losses = results["Return"].clip(upper=0)
    ax.fill_between(results.index, losses, 0, color="gray", alpha=0.4, label="Actual Loss")
    ax.plot(results.index, -results[var_col], color=color, linewidth=1.0, label=title)
    ax.plot(results.index, -results["FHS_VaR"],
            color="#D6604D", linewidth=0.8, linestyle="--", alpha=0.6, label="FHS baseline")
    ex_dates = results[results[ex_col] == 1]
    ax.scatter(ex_dates.index, ex_dates["Return"],
               color="black", s=12, zorder=5, label=f"Exception (n={len(ex_dates)})")
    ax.set_ylabel("Daily Return", fontsize=13)
    ax.set_title(title, fontsize=13, fontweight="bold")
    ax.legend(loc="lower left", fontsize=10, ncol=2)
    ax.set_ylim(-0.15, 0.05)
    ax.axhline(0, color="black", linewidth=0.5)
    ax.grid(axis="y", alpha=0.3)
    ax.tick_params(axis="both", labelsize=12)

plt.tight_layout()
plt.savefig(DATA_PATH + "fig_garch1_extensions.png", dpi=150, bbox_inches="tight")
plt.show()

cov = results["2020-01-01":"2020-12-31"]

fig2, axes = plt.subplots(3, 1, figsize=(16, 12), sharex=True)
fig2.suptitle("GARCH Extensions — COVID-19 Crash (2020)\nAdaptation Speed Comparison",
              fontsize=14, fontweight="bold")

for ax, (var_col, ex_col, title, color) in zip(axes, plot_models):
    losses = cov["Return"].clip(upper=0)
    ax.fill_between(cov.index, losses, 0, color="gray", alpha=0.4, label="Actual Loss")
    ax.plot(cov.index, -cov[var_col], color=color, linewidth=1.8, label=title)
    ax.plot(cov.index, -cov["FHS_VaR"],
            color="#D6604D", linewidth=1.2, linestyle="--", alpha=0.7, label="FHS baseline")
    ex_dates = cov[cov[ex_col] == 1]
    ax.scatter(ex_dates.index, ex_dates["Return"],
               color="black", s=30, zorder=5, label=f"Exception (n={len(ex_dates)})")
    ax.set_ylabel("Daily Return", fontsize=12)
    ax.set_title(title, fontsize=12, fontweight="bold")
    ax.legend(loc="lower left", fontsize=10, ncol=2)
    ax.axhline(0, color="black", linewidth=0.5)
    ax.grid(axis="y", alpha=0.3)
    ax.tick_params(axis="both", labelsize=11)

plt.tight_layout()
plt.savefig(DATA_PATH + "fig_garch2_covid.png", dpi=150, bbox_inches="tight")
plt.show()

regime_order = [
    "Pre-GFC","GFC","Recovery","Low-Vol Bull",
    "COVID","Post-COVID","2022 Bear",
    "2023 Recovery","2024 AI Rally","2025-2026"
]

summary = []
for regime in regime_order:
    sub = results[results["Regime"] == regime]
    if len(sub) == 0:
        continue
    summary.append({
        "Regime":    regime,
        "FHS":       sub["Ex_FHS"].sum(),
        "GJR":       sub["Ex_GJR"].sum(),
        "t-GARCH":   sub["Ex_tGARCH"].sum(),
        "GARCH-EVT": sub["Ex_GARCH_EVT"].sum(),
        "Theory":    round(len(sub) * 0.01, 1),
    })
sumdf = pd.DataFrame(summary)

fig3, ax = plt.subplots(figsize=(18, 7))
x     = np.arange(len(sumdf))
width = 0.18
ax.bar(x - 1.5*width, sumdf["FHS"],       width, label="FHS (baseline)", color="#D6604D", alpha=0.85)
ax.bar(x - 0.5*width, sumdf["GJR"],       width, label="GJR-GARCH",      color="#E07B39", alpha=0.85)
ax.bar(x + 0.5*width, sumdf["t-GARCH"],   width, label="t-GARCH",        color="#1A9850", alpha=0.85)
ax.bar(x + 1.5*width, sumdf["GARCH-EVT"], width, label="GARCH-EVT",      color="#7B2D8B", alpha=0.85)
ax.step(x, sumdf["Theory"], where="mid", color="black", linewidth=2, linestyle="--", label="Theory (1%)")
ax.axhline(4,  color="#1A9850", linestyle=":", linewidth=1.5, alpha=0.8)
ax.axhline(9,  color="#FFA500", linestyle=":", linewidth=1.5, alpha=0.8)
ax.axhline(10, color="#D65F5F", linestyle=":", linewidth=1.5, alpha=0.8)
ax.set_xticks(x)
ax.set_xticklabels(sumdf["Regime"], rotation=25, ha="right", fontsize=12)
ax.set_ylabel("Number of Exceptions", fontsize=13)
ax.set_title("GARCH Extensions vs FHS — Exceptions by Regime", fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig(DATA_PATH + "fig_garch3_regime.png", dpi=150, bbox_inches="tight")
plt.show()

results.to_csv(DATA_PATH + "var_results_part2.csv")
print("Saved.")
