##### Beyond VaR: 04 — DCC-GARCH
##### Requires var_results_part2.csv generated by 03_garch_extensions.py
##### Download data files from the beyond-var/ folder in this repository,
##### then update DATA_PATH below to match your local directory.

import pandas as pd
import numpy as np
from scipy import stats
from scipy.optimize import minimize
from arch import arch_model
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

DATA_PATH = r"C:/Users/your_username/Downloads/"  # update this to your local path

returns = pd.read_csv(DATA_PATH + "returns.csv", index_col=0, parse_dates=True)
results = pd.read_csv(DATA_PATH + "var_results_part2.csv", index_col=0, parse_dates=True)
spy_ret = returns["SPY"].reindex(results.index)
tlt_ret = returns["TLT"].reindex(results.index)

REGIME_COLORS = {
    "Pre-GFC":       "#4878CF",
    "GFC":           "#D65F5F",
    "Recovery":      "#6ACC65",
    "Low-Vol Bull":  "#B47CC7",
    "COVID":         "#C4AD66",
    "Post-COVID":    "#77BEDB",
    "2022 Bear":     "#D65F5F",
    "2023 Recovery": "#6ACC65",
    "2024 AI Rally": "#4878CF",
    "2025-2026":     "#B47CC7",
}

def add_regime_bands(ax):
    for regime, color in REGIME_COLORS.items():
        sub = results[results["Regime"] == regime]
        if len(sub) == 0:
            continue
        ax.axvspan(sub.index[0], sub.index[-1], alpha=0.08, color=color)

s1  = spy_ret.dropna().values * 100
s2  = tlt_ret.dropna().values * 100
idx = spy_ret.dropna().index

print("Full-period GARCH fitting...")
res1 = arch_model(s1, vol="GARCH", p=1, q=1, dist="normal", rescale=False).fit(disp="off")
res2 = arch_model(s2, vol="GARCH", p=1, q=1, dist="normal", rescale=False).fit(disp="off")
z1   = res1.std_resid
z2   = res2.std_resid
print("Done.")

Q_bar = np.cov(z1, z2)

def dcc_loglik(params):
    a, b = params
    if a <= 0 or b <= 0 or a + b >= 1:
        return np.inf
    Q  = Q_bar.copy()
    ll = 0.0
    for t in range(1, len(z1)):
        z_outer = np.outer([z1[t-1], z2[t-1]], [z1[t-1], z2[t-1]])
        Q = (1 - a - b) * Q_bar + a * z_outer + b * Q
        q11 = Q[0, 0]
        q22 = Q[1, 1]
        q12 = Q[0, 1]
        if q11 <= 0 or q22 <= 0:
            return np.inf
        rho = q12 / np.sqrt(q11 * q22)
        rho = np.clip(rho, -0.999, 0.999)
        ll += np.log(1 - rho**2) + \
              (z1[t]**2 + z2[t]**2 - 2*rho*z1[t]*z2[t]) / (1 - rho**2) - \
              (z1[t]**2 + z2[t]**2)
    return ll

print("DCC MLE estimation...")
result = minimize(dcc_loglik, x0=[0.05, 0.93],
                  method="L-BFGS-B",
                  bounds=[(1e-6, 0.5), (1e-6, 0.999)])
a_opt, b_opt = result.x
print(f"Done. alpha={a_opt:.4f}, beta={b_opt:.4f}")

rho_dcc = np.full(len(z1), np.nan)
Q = Q_bar.copy()
for t in range(1, len(z1)):
    z_outer = np.outer([z1[t-1], z2[t-1]], [z1[t-1], z2[t-1]])
    Q = (1 - a_opt - b_opt) * Q_bar + a_opt * z_outer + b_opt * Q
    rho = Q[0, 1] / np.sqrt(Q[0, 0] * Q[1, 1])
    rho_dcc[t] = np.clip(rho, -0.999, 0.999)

rho_dcc_series = pd.Series(rho_dcc, index=idx)
roll_corr      = spy_ret.rolling(60).corr(tlt_ret)
roll_corr_20   = spy_ret.rolling(20).corr(tlt_ret)

regime_order = [
    "Pre-GFC","GFC","Recovery","Low-Vol Bull",
    "COVID","Post-COVID","2022 Bear",
    "2023 Recovery","2024 AI Rally","2025-2026"
]

print(f"\n{'Regime':<18} {'DCC':>8} {'Roll-60':>8} {'Roll-20':>8}")
print("-" * 46)

regime_summary = []
for regime in regime_order:
    sub = results[results["Regime"] == regime]
    if len(sub) == 0:
        continue
    sub_idx   = sub.index
    dcc_mean  = rho_dcc_series.reindex(sub_idx).mean()
    r60_mean  = roll_corr.reindex(sub_idx).mean()
    r20_mean  = roll_corr_20.reindex(sub_idx).mean()
    print(f"{regime:<18} {dcc_mean:>8.3f} {r60_mean:>8.3f} {r20_mean:>8.3f}")
    regime_summary.append({"Regime": regime, "DCC": dcc_mean, "Roll60": r60_mean, "Roll20": r20_mean})

bear_2022 = results[results["Regime"] == "2022 Bear"].index
print(f"\n2022 Bear Correlation Analysis:")
print(f"  DCC average:         {rho_dcc_series.reindex(bear_2022).mean():.3f}")
print(f"  Rolling-60 average:  {roll_corr.reindex(bear_2022).mean():.3f}")
print(f"  DCC positive days:   {(rho_dcc_series.reindex(bear_2022) > 0).sum()}")
print(f"  Roll-60 positive:    {(roll_corr.reindex(bear_2022) > 0).sum()}")

dcc_pos_first  = rho_dcc_series.reindex(bear_2022)[rho_dcc_series.reindex(bear_2022) > 0].index
roll_pos_first = roll_corr.reindex(bear_2022)[roll_corr.reindex(bear_2022) > 0].index
if len(dcc_pos_first) > 0:
    print(f"  DCC first positive:     {dcc_pos_first[0].date()}")
if len(roll_pos_first) > 0:
    print(f"  Roll-60 first positive: {roll_pos_first[0].date()}")

fig1, ax = plt.subplots(figsize=(18, 6))
add_regime_bands(ax)
ax.plot(rho_dcc_series.index, rho_dcc_series,
        color="#2166AC", linewidth=1.2, label=f"DCC-GARCH (alpha={a_opt:.3f}, beta={b_opt:.3f})")
ax.plot(roll_corr.index, roll_corr,
        color="#D6604D", linewidth=0.8, linestyle="--", alpha=0.7, label="60-day Rolling Correlation")
ax.axhline(0, color="black", linewidth=0.8, linestyle="--")
ax.fill_between(rho_dcc_series.index, rho_dcc_series, 0,
                where=(rho_dcc_series > 0), color="#D6604D", alpha=0.2)
ax.fill_between(rho_dcc_series.index, rho_dcc_series, 0,
                where=(rho_dcc_series < 0), color="#2166AC", alpha=0.15)
ax.axvspan(pd.Timestamp("2022-01-01"), pd.Timestamp("2022-12-31"),
           color="orange", alpha=0.15, label="2022 Bear")
ax.set_ylabel("Correlation (SPY vs TLT)", fontsize=13)
ax.set_title("DCC-GARCH (Full-Period MLE) vs Rolling Correlation — SPY/TLT (2005-2026)",
             fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(alpha=0.3)
ax.tick_params(axis="both", labelsize=12)
plt.tight_layout()
plt.savefig(DATA_PATH + "fig_dcc1_correlation.png", dpi=150, bbox_inches="tight")
plt.show()

zoom     = rho_dcc_series["2021-01-01":"2023-12-31"]
zoom_r60 = roll_corr["2021-01-01":"2023-12-31"]
zoom_r20 = roll_corr_20["2021-01-01":"2023-12-31"]

fig2, ax = plt.subplots(figsize=(16, 6))
ax.plot(zoom.index, zoom, color="#2166AC", linewidth=1.8,
        label=f"DCC-GARCH (alpha={a_opt:.3f}, beta={b_opt:.3f})")
ax.plot(zoom_r60.index, zoom_r60, color="#D6604D", linewidth=1.2,
        linestyle="--", alpha=0.8, label="60-day Rolling Correlation")
ax.plot(zoom_r20.index, zoom_r20, color="#1A9850", linewidth=1.0,
        linestyle=":", alpha=0.8, label="20-day Rolling Correlation")
ax.axhline(0, color="black", linewidth=1.0, linestyle="--")
ax.axvspan(pd.Timestamp("2022-01-01"), pd.Timestamp("2022-12-31"),
           color="orange", alpha=0.12, label="2022 Bear")
ax.set_ylabel("Correlation (SPY vs TLT)", fontsize=13)
ax.set_title("2022 Correlation Breakdown — Detection Speed\nDCC-GARCH vs Rolling Correlation",
             fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(alpha=0.3)
ax.tick_params(axis="both", labelsize=12)
plt.tight_layout()
plt.savefig(DATA_PATH + "fig_dcc2_2022.png", dpi=150, bbox_inches="tight")
plt.show()

sumdf = pd.DataFrame(regime_summary)
fig3, ax = plt.subplots(figsize=(16, 6))
x     = np.arange(len(sumdf))
width = 0.28
ax.bar(x - width, sumdf["DCC"],    width, label="DCC-GARCH",          color="#2166AC", alpha=0.85)
ax.bar(x,         sumdf["Roll60"], width, label="60-day Rolling Corr", color="#D6604D", alpha=0.85)
ax.bar(x + width, sumdf["Roll20"], width, label="20-day Rolling Corr", color="#1A9850", alpha=0.85)
ax.axhline(0, color="black", linewidth=0.8, linestyle="--")
ax.set_xticks(x)
ax.set_xticklabels(sumdf["Regime"], rotation=25, ha="right", fontsize=12)
ax.set_ylabel("Average Correlation", fontsize=13)
ax.set_title("Average SPY/TLT Correlation by Regime", fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig(DATA_PATH + "fig_dcc3_regime_corr.png", dpi=150, bbox_inches="tight")
plt.show()

sig1_series = pd.Series(res1.conditional_volatility / 100, index=idx)
sig2_series = pd.Series(res2.conditional_volatility / 100, index=idx)

fig4, axes = plt.subplots(3, 1, figsize=(18, 12), sharex=True)
fig4.suptitle("DCC-GARCH Components — Volatility and Correlation",
              fontsize=14, fontweight="bold")

axes[0].plot(sig1_series.index, sig1_series * 100, color="#2166AC", linewidth=1.0)
axes[0].set_ylabel("Conditional Vol (%)", fontsize=12)
axes[0].set_title("SPY Conditional Volatility (GARCH)", fontsize=12, fontweight="bold")
axes[0].grid(alpha=0.3)
add_regime_bands(axes[0])

axes[1].plot(sig2_series.index, sig2_series * 100, color="#1A9850", linewidth=1.0)
axes[1].set_ylabel("Conditional Vol (%)", fontsize=12)
axes[1].set_title("TLT Conditional Volatility (GARCH)", fontsize=12, fontweight="bold")
axes[1].grid(alpha=0.3)
add_regime_bands(axes[1])

axes[2].plot(rho_dcc_series.index, rho_dcc_series, color="#D6604D", linewidth=1.0)
axes[2].axhline(0, color="black", linewidth=0.8, linestyle="--")
axes[2].fill_between(rho_dcc_series.index, rho_dcc_series, 0,
                     where=(rho_dcc_series > 0), color="#D6604D", alpha=0.3)
axes[2].fill_between(rho_dcc_series.index, rho_dcc_series, 0,
                     where=(rho_dcc_series < 0), color="#2166AC", alpha=0.2)
axes[2].set_ylabel("DCC Correlation", fontsize=12)
axes[2].set_title("DCC-GARCH Conditional Correlation (SPY vs TLT)", fontsize=12, fontweight="bold")
axes[2].grid(alpha=0.3)
add_regime_bands(axes[2])
axes[2].tick_params(axis="x", labelsize=12)

plt.tight_layout()
plt.savefig(DATA_PATH + "fig_dcc4_components.png", dpi=150, bbox_inches="tight")
plt.show()

print("Saved (visualization only — no csv update needed for DCC).")
