##### Beyond VaR: 05 — Model Validation
##### Requires var_results_part2.csv generated by 03_garch_extensions.py
##### Download data files from the beyond-var/ folder in this repository,
##### then update DATA_PATH below to match your local directory.

import pandas as pd
import numpy as np
from scipy import stats
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

DATA_PATH = r"C:/Users/your_username/Downloads/"  # update this to your local path

returns = pd.read_csv(DATA_PATH + "returns.csv", index_col=0, parse_dates=True)
results = pd.read_csv(DATA_PATH + "var_results_part2.csv", index_col=0, parse_dates=True)
spy_ret = returns["SPY"].reindex(results.index)
losses  = -spy_ret.dropna().values

REGIME_COLORS = {
    "Pre-GFC":       "#4878CF",
    "GFC":           "#D65F5F",
    "Recovery":      "#6ACC65",
    "Low-Vol Bull":  "#B47CC7",
    "COVID":         "#C4AD66",
    "Post-COVID":    "#77BEDB",
    "2022 Bear":     "#D65F5F",
    "2023 Recovery": "#6ACC65",
    "2024 AI Rally": "#4878CF",
    "2025-2026":     "#B47CC7",
}

def add_regime_bands(ax):
    for regime, color in REGIME_COLORS.items():
        sub = results[results["Regime"] == regime]
        if len(sub) == 0:
            continue
        ax.axvspan(sub.index[0], sub.index[-1], alpha=0.08, color=color)

def rolling_kupiec_pval(exceptions, window=250, p=0.01):
    ex    = exceptions.values
    n     = len(ex)
    pvals = np.full(n, np.nan)
    for t in range(window, n):
        x = ex[t - window:t].sum()
        if x == 0 or x == window:
            pvals[t] = np.nan
            continue
        p_hat = x / window
        lr    = -2 * (x * np.log(p / p_hat) + (window - x) * np.log((1 - p) / (1 - p_hat)))
        pvals[t] = 1 - stats.chi2.cdf(lr, df=1)
    return pd.Series(pvals, index=exceptions.index)

def fit_gpd(exceedances):
    def neg_ll(params):
        xi, beta = params
        if beta <= 0:
            return np.inf
        if xi != 0:
            if np.any(1 + xi * exceedances / beta <= 0):
                return np.inf
            return np.sum(np.log(beta) + (1 + 1/xi) * np.log(1 + xi * exceedances / beta))
        else:
            return np.sum(np.log(beta) + exceedances / beta)
    result = minimize(neg_ll, x0=[0.1, np.std(exceedances)], method="Nelder-Mead")
    return result.x

models_kupiec = {
    "Parametric": "Ex_Param",
    "HS":         "Ex_HS",
    "FHS":        "Ex_FHS",
    "sVaR":       "Ex_sVaR_Combined",
    "GJR-GARCH":  "Ex_GJR",
    "t-GARCH":    "Ex_tGARCH",
    "GARCH-EVT":  "Ex_GARCH_EVT",
}

print("Rolling Kupiec p-values...")
pval_series = {}
for name, col in models_kupiec.items():
    pval_series[name] = rolling_kupiec_pval(results[col].fillna(0))
    print(f"  {name} done.")
print("Done.\n")

thresholds_q = np.arange(0.85, 0.98, 0.01)
var_99   = []
es_975   = []
xi_list  = []
n_exceed = []

for q in thresholds_q:
    u      = np.quantile(losses, q)
    excess = losses[losses > u] - u
    n      = len(losses)
    n_u    = len(excess)
    if n_u < 10:
        var_99.append(np.nan)
        es_975.append(np.nan)
        xi_list.append(np.nan)
        n_exceed.append(n_u)
        continue
    xi, beta = fit_gpd(excess)
    n_exceed.append(n_u)
    xi_list.append(xi)
    p_var = 0.01
    p_es  = 0.025
    if xi != 0:
        v = u + (beta/xi) * (((p_var * n / n_u) ** (-xi)) - 1)
        e = u + (beta/xi) * (((p_es  * n / n_u) ** (-xi)) - 1)
    else:
        v = u + beta * np.log(p_var * n / n_u)
        e = u + beta * np.log(p_es  * n / n_u)
    var_99.append(v * 100)
    es_975.append(e * 100)

colors_map = {
    "Parametric": "#2166AC",
    "HS":         "#1A9850",
    "FHS":        "#D6604D",
    "sVaR":       "#7B2D8B",
    "GJR-GARCH":  "#E07B39",
    "t-GARCH":    "#006400",
    "GARCH-EVT":  "#8B0000",
}

fig1, axes = plt.subplots(4, 1, figsize=(18, 18), sharex=True)
fig1.suptitle("Rolling Kupiec p-values (250-Day Window)\np < 0.05 indicates active model failure",
              fontsize=16, fontweight="bold")

groups = [
    ["Parametric", "HS", "FHS"],
    ["sVaR"],
    ["GJR-GARCH", "t-GARCH"],
    ["GARCH-EVT"],
]
group_titles = [
    "Part 1 Models: Parametric / HS / FHS",
    "Stressed VaR (Combined)",
    "GARCH Extensions: GJR / t-GARCH",
    "GARCH-EVT",
]

for ax, group, title in zip(axes, groups, group_titles):
    add_regime_bands(ax)
    for name in group:
        pvals = pval_series[name]
        ax.plot(pvals.index, pvals, color=colors_map[name], linewidth=1.0, label=name)
        ax.fill_between(pvals.index, pvals, 0.05,
                        where=(pvals < 0.05), color=colors_map[name], alpha=0.15)
    ax.axhline(0.05, color="black", linewidth=1.2, linestyle="--", label="p = 0.05 threshold")
    ax.set_ylabel("Kupiec p-value", fontsize=12)
    ax.set_title(title, fontsize=12, fontweight="bold")
    ax.set_ylim(-0.05, 1.05)
    ax.legend(loc="upper right", fontsize=10)
    ax.grid(axis="y", alpha=0.3)
    ax.tick_params(axis="both", labelsize=11)

axes[-1].tick_params(axis="x", labelsize=12)
plt.tight_layout()
plt.savefig(DATA_PATH + "fig_val1_rolling_kupiec.png", dpi=150, bbox_inches="tight")
plt.show()

fig2, axes = plt.subplots(3, 1, figsize=(14, 12))
fig2.suptitle("EVT Threshold Sensitivity Analysis",
              fontsize=14, fontweight="bold")

axes[0].plot(thresholds_q * 100, var_99, color="#2166AC", linewidth=2,
             marker="o", markersize=5, label="99% VaR")
axes[0].plot(thresholds_q * 100, es_975, color="#D6604D", linewidth=2,
             marker="s", markersize=5, label="97.5% ES")
axes[0].axvline(95, color="black", linewidth=1.2, linestyle="--", label="95th (baseline)")
axes[0].set_ylabel("Estimate (%)", fontsize=12)
axes[0].set_title("VaR and ES vs Threshold", fontsize=12, fontweight="bold")
axes[0].legend(fontsize=11)
axes[0].grid(alpha=0.3)

axes[1].plot(thresholds_q * 100, xi_list, color="#7B2D8B", linewidth=2,
             marker="o", markersize=5)
axes[1].axhline(0, color="black", linewidth=0.8, linestyle="--")
axes[1].axvline(95, color="black", linewidth=1.2, linestyle="--")
axes[1].set_ylabel("xi (shape)", fontsize=12)
axes[1].set_title("GPD Shape Parameter xi vs Threshold", fontsize=12, fontweight="bold")
axes[1].grid(alpha=0.3)

axes[2].bar(thresholds_q * 100, n_exceed, width=0.7, color="#1A9850", alpha=0.8)
axes[2].axvline(95, color="black", linewidth=1.2, linestyle="--", label="95th (baseline)")
axes[2].axhline(50, color="#D6604D", linewidth=1.2, linestyle=":", label="Minimum recommended (50)")
axes[2].set_xlabel("Threshold Percentile", fontsize=12)
axes[2].set_ylabel("N Exceedances", fontsize=12)
axes[2].set_title("Number of Exceedances vs Threshold", fontsize=12, fontweight="bold")
axes[2].legend(fontsize=11)
axes[2].grid(axis="y", alpha=0.3)

for ax in axes:
    ax.tick_params(axis="both", labelsize=11)

plt.tight_layout()
plt.savefig(DATA_PATH + "fig_val2_evt_sensitivity.png", dpi=150, bbox_inches="tight")
plt.show()

regime_order = [
    "Pre-GFC","GFC","Recovery","Low-Vol Bull",
    "COVID","Post-COVID","2022 Bear",
    "2023 Recovery","2024 AI Rally","2025-2026"
]

heatmap_data = {}
for name in models_kupiec.keys():
    pvals = pval_series[name]
    row   = []
    for regime in regime_order:
        sub = results[results["Regime"] == regime]
        if len(sub) == 0:
            row.append(np.nan)
            continue
        p_regime = pvals.reindex(sub.index).dropna()
        pct_fail = (p_regime < 0.05).mean() if len(p_regime) > 0 else np.nan
        row.append(pct_fail)
    heatmap_data[name] = row

heatmap_df = pd.DataFrame(heatmap_data, index=regime_order).T

fig3, ax = plt.subplots(figsize=(16, 7))
im = ax.imshow(heatmap_df.values, cmap="RdYlGn_r", vmin=0, vmax=1, aspect="auto")

ax.set_xticks(range(len(regime_order)))
ax.set_xticklabels(regime_order, rotation=30, ha="right", fontsize=11)
ax.set_yticks(range(len(heatmap_df.index)))
ax.set_yticklabels(heatmap_df.index, fontsize=11)

for i in range(len(heatmap_df.index)):
    for j in range(len(regime_order)):
        val = heatmap_df.values[i, j]
        if not np.isnan(val):
            ax.text(j, i, f"{val:.0%}", ha="center", va="center",
                    fontsize=10, fontweight="bold",
                    color="white" if val > 0.6 else "black")

plt.colorbar(im, ax=ax, label="Fraction of Days with p < 0.05")
ax.set_title("Model Failure Heatmap — Fraction of Days Failing Kupiec Test by Regime",
             fontsize=13, fontweight="bold", pad=15)

plt.tight_layout()
plt.savefig(DATA_PATH + "fig_val3_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()

print("Saved.")
